Const
{# Whites}                    
  border                = 0;
  antique_white         = 1;  
  azure                 = 2;  
  bisque                = 3;  
  blanched_almond       = 4;  
  cornsilk              = 5;  
  eggshell              = 6;  
  floral_white          = 7;  
  gainsboro             = 8;  
  ghost_white           = 9;  
  honeydew              = 10; 
  ivory                 = 11; 
  lavender              = 12; 
  lavender_blush        = 13; 
  lemon_chiffon         = 14; 
  linen                 = 15; 
  mint_cream            = 16; 
  misty_rose            = 17; 
  moccasin              = 18; 
  navajo_white          = 19; 
  old_lace              = 20; 
  papaya_whip           = 21; 
  peach_puff            = 22; 
  seashell              = 23; 
  snow                  = 24; 
  thistle               = 25; 
  titanium_white        = 26; 
  wheat                 = 27; 
  white                 = 28; 
  white_smoke           = 29; 
  zinc_white            = 30;
{#Gray}
  cold_grey             = 31;
  dim_grey              = 32;
  grey                  = 33;
  light_grey            = 34;
  slate_grey            = 35;
  slate_grey_dark       = 36; 
  slate_grey_light      = 37; 
  warm_grey             = 38;
{# Blacks}
  black                 = 39;
  ivory_black           = 40;
  lamp_black            = 41;
{# Reds}
  alizarin_crimson      = 42;
  brick                 = 43; 
  cadmium_red_deep      = 44; 
  coral                 = 45; 
  coral_light           = 46; 
  deep_pink             = 47; 
  english_red           = 48; 
  firebrick             = 49; 
  geranium_lake         = 50; 
  hot_pink              = 51; 
  indian_red            = 52; 
  light_salmon          = 53; 
  madder_lake_deep      = 54; 
  maroon                = 55; 
  pink                  = 56; 
  pink_light            = 57; 
  raspberry             = 58; 
  red                   = 59; 
  rose_madder           = 60; 
  salmon                = 61; 
  tomato                = 62; 
  venetian_red          =     
{# Browns}                63; 
  beige                 = 64; 
  brown                 = 65; 
  brown_madder          = 66; 
  brown_ochre           = 67; 
  burlywood             = 68; 
  burnt_sienna          = 69; 
  burnt_umber           = 70; 
  chocolate             = 71; 
  deep_ochre            = 72; 
  flesh                 = 73; 
  flesh_ochre           = 74; 
  gold_ochre            = 75; 
  greenish_umber        = 76; 
  khaki                 = 77; 
  khaki_dark            = 78; 
  light_beige           = 79; 
  peru                  = 80; 
  rosy_brown            = 81; 
  raw_sienna            = 82; 
  raw_umber             = 83; 
  sepia                 = 84; 
  sienna                = 85; 
  saddle_brown          = 86; 
  sandy_brown           = 87;
  tan                   = 88;
  van_dyke_brown        = 89;
{# Oranges}
  cadmium_orange        = 90;
  cadmium_red_light     = 91;
  carrot                = 92;
  dark_orange           = 93;
  mars_orange           = 94;
  mars_yellow           = 95;
  orange                = 96;
  orange_red            = 97;
  yellow_ochre          = 98;
{# Yellows}
  aureoline_yellow      = 99;
  banana                = 100;
  cadmium_lemon         = 101;
  cadmium_yellow        = 102;
  cadmium_yellow_light  = 103;
  gold                  = 104;
  goldenrod             = 105;
  goldenrod_dark        = 106;
  goldenrod_light       = 107;
  goldenrod_pale        = 108;
  light_goldenrod       = 109;
  melon                 = 110;
  naples_yellow_deep    = 111;
  yellow                = 112;
  yellow_light          = 113;
{# Greens}
  chartreuse            = 114;
  chrome_oxide_green    = 115;
  cinnabar_green        = 116;
  cobalt_green          = 117;
  emerald_green         = 118;
  forest_green          = 119;
  green                 = 120;
  green_dark            = 121;
  green_pale            = 122;
  green_yellow          = 123;
  lawn_green            = 124;
  lime_green            = 125;
  mint                  = 126;
  olive                 = 127;
  olive_drab            = 128;
  olive_green_dark      = 129;
  permanent_green       = 130;
  sap_green             = 131;
  sea_green             = 132;
  sea_green_dark        = 133;
  sea_green_medium      = 134;
  sea_green_light       = 135;
  spring_green          = 136;
  spring_green_medium   = 137;
  terre_verte           = 138;
  viridian_light        = 139;
  yellow_green          = 140;
{# Cyans}
  aquamarine            = 141;
  aquamarine_medium     = 142;
  cyan                  = 143;
  cyan_white            = 144;
  turquoise             = 145;
  turquoise_dark        = 146;
  turquoise_medium      = 147;
  turquoise_pale        = 148;
{# Blues}
  alice_blue            = 149;
  blue                  = 150;
  blue_light            = 151;
  blue_medium           = 152;
  cadet                 = 153;
  cobalt                = 154;
  cornflower            = 155;
  cerulean              = 156;
  dodger_blue           = 157;
  indigo                = 158;
  manganese_blue        = 159;
  midnight_blue         = 160;
  navy                  = 161;
  peacock               = 162;
  powder_blue           = 163;
  royal_blue            = 164;
  slate_blue            = 165;
  slate_blue_dark       = 166;
  slate_blue_light      = 167;
  slate_blue_medium     = 168;
  sky_blue              = 169;
  sky_blue_deep         = 170;
  sky_blue_light        = 171;
  steel_blue            = 172;
  steel_blue_light      = 173;
  turquoise_blue        = 174;
  ultramarine           =     
{# Magentas}              175;
  blue_violet           = 176;
  cobalt_violet_deep    = 177;
  magenta               = 178;
  orchid                = 179;
  orchid_dark           = 180;
  orchid_medium         = 181;
  permanent_red_violet  = 182;
  plum                  = 183;
  purple                = 184;
  purple_medium         = 185;
  ultramarine_violet    = 186;
  violet                = 187;
  violet_dark           = 188;
  violet_red            = 189;
  violet_red_medium     = 190;
  violet_red_pale       = 191;

Palette:Array[0..255] of Record R,G,B:Byte End = (
(R:  0;G:  0;B:  0),(R:250;G:235;B:215),(R:240;G:255;B:255),(R:255;G:228;B:196),(R:255;G:235;B:205),(R:255;G:248;B:220),
(R:252;G:230;B:201),(R:255;G:250;B:240),(R:220;G:220;B:220),(R:248;G:248;B:255),(R:240;G:255;B:240),(R:255;G:255;B:240),
(R:230;G:230;B:250),(R:255;G:240;B:245),(R:255;G:250;B:205),(R:250;G:240;B:230),(R:245;G:255;B:250),(R:255;G:228;B:225),
(R:255;G:228;B:181),(R:255;G:222;B:173),(R:253;G:245;B:230),(R:255;G:239;B:213),(R:255;G:218;B:185),(R:255;G:245;B:238),
(R:255;G:250;B:250),(R:216;G:191;B:216),(R:252;G:255;B:240),(R:245;G:222;B:179),(R:255;G:255;B:255),(R:245;G:245;B:245),
(R:253;G:248;B:255),(R:128;G:138;B:135),(R:105;G:105;B:105),(R:192;G:192;B:192),(R:211;G:211;B:211),(R:112;G:128;B:144),
(R: 47;G: 79;B: 79),(R:119;G:136;B:153),(R:128;G:128;B:105),(R:  0;G:  0;B:  0),(R: 41;G: 36;B: 33),(R: 46;G: 71;B: 59),
(R:227;G: 38;B: 54),(R:156;G:102;B: 31),(R:227;G: 23;B: 13),(R:255;G:127;B: 80),(R:240;G:128;B:128),(R:255;G: 20;B:147),
(R:212;G: 61;B: 26),(R:178;G: 34;B: 34),(R:227;G: 18;B: 48),(R:255;G:105;B:180),(R:176;G: 23;B: 31),(R:255;G:160;B:122),
(R:227;G: 46;B: 48),(R:176;G: 48;B: 96),(R:255;G:192;B:203),(R:255;G:182;B:193),(R:135;G: 38;B: 87),(R:255;G:  0;B:  0),
(R:227;G: 54;B: 56),(R:250;G:128;B:114),(R:255;G: 99;B: 71),(R:212;G: 26;B: 31),(R:163;G:148;B:128),(R:128;G: 42;B: 42),
(R:219;G: 41;B: 41),(R:135;G: 66;B: 31),(R:222;G:184;B:135),(R:138;G: 54;B: 15),(R:138;G: 51;B: 36),(R:210;G:105;B: 30),
(R:115;G: 61;B: 26),(R:255;G:125;B: 64),(R:255;G: 87;B: 33),(R:199;G:120;B: 38),(R:255;G: 61;B: 13),(R:240;G:230;B:140),
(R:189;G:183;B:107),(R:245;G:245;B:220),(R:205;G:133;B: 63),(R:188;G:143;B:143),(R:199;G: 97;B: 20),(R:115;G: 74;B: 18),
(R: 94;G: 38;B: 18),(R:160;G: 82;B: 45),(R:139;G: 69;B: 19),(R:244;G:164;B: 96),(R:210;G:180;B:140),(R: 94;G: 38;B:  5),
(R:255;G: 97;B:  3),(R:255;G:  3;B: 13),(R:237;G:145;B: 33),(R:255;G:140;B:  0),(R:150;G: 69;B: 20),(R:227;G:112;B: 26),
(R:255;G:128;B:  0),(R:255;G: 69;B:  0),(R:227;G:130;B: 23),(R:255;G:168;B: 36),(R:227;G:207;B: 87),(R:255;G:227;B:  3),
(R:255;G:153;B: 18),(R:255;G:176;B: 15),(R:255;G:215;B:  0),(R:218;G:165;B: 32),(R:184;G:134;B: 11),(R:250;G:250;B:210),
(R:238;G:232;B:170),(R:238;G:221;B:130),(R:227;G:168;B:105),(R:255;G:168;B: 18),(R:255;G:255;B:  0),(R:255;G:255;B:224),
(R:127;G:255;B:  0),(R:102;G:128;B: 20),(R: 97;G:179;B: 41),(R: 61;G:145;B: 64),(R:  0;G:201;B: 87),(R: 34;G:139;B: 34),
(R:  0;G:255;B:  0),(R:  0;G:100;B:  0),(R:152;G:251;B:152),(R:173;G:255;B: 47),(R:124;G:252;B:  0),(R: 50;G:205;B: 50),
(R:189;G:252;B:201),(R: 59;G: 94;B: 43),(R:107;G:142;B: 35),(R: 85;G:107;B: 47),(R: 10;G:201;B: 43),(R: 48;G:128;B: 20),
(R: 46;G:139;B: 87),(R:143;G:188;B:143),(R: 60;G:179;B:113),(R: 32;G:178;B:170),(R:  0;G:255;B:127),(R:  0;G:250;B:154),
(R: 56;G: 94;B: 15),(R:110;G:255;B:112),(R:154;G:205;B: 50),(R:127;G:255;B:212),(R:102;G:205;B:170),(R:  0;G:255;B:255),
(R:224;G:255;B:255),(R: 64;G:224;B:208),(R:  0;G:206;B:209),(R: 72;G:209;B:204),(R:175;G:238;B:238),(R:240;G:248;B:255),
(R:  0;G:  0;B:255),(R:173;G:216;B:230),(R:  0;G:  0;B:205),(R: 95;G:158;B:160),(R: 61;G: 89;B:171),(R:100;G:149;B:237),
(R:  5;G:184;B:204),(R:30 ;G:44 ;B:55 ),(R:  8;G: 46;B: 84),(R:  3;G:168;B:158),(R: 25;G: 25;B:112),(R:  0;G:  0;B:128),
(R: 51;G:161;B:201),(R:176;G:224;B:230),(R: 65;G:105;B:225),(R:106;G: 90;B:205),(R: 72;G: 61;B:139),(R:132;G:112;B:255),
(R:123;G:104;B:238),(R:135;G:206;B:235),(R:  0;G:191;B:255),(R:135;G:206;B:250),(R: 70;G:130;B:180),(R:176;G:196;B:222),
(R:  0;G:199;B:140),(R: 18;G: 10;B:143),(R:138;G: 43;B:226),(R:145;G: 33;B:158),(R:255;G:  0;B:255),(R:218;G:112;B:214),
(R:153;G: 50;B:204),(R:186;G: 85;B:211),(R:219;G: 38;B: 69),(R:221;G:160;B:221),(R:160;G: 32;B:240),(R:147;G:112;B:219),
(R: 92;G: 36;B:110),(R:143;G: 94;B:153),(R:148;G:  0;B:211),(R:208;G: 32;B:144),(R:199;G: 21;B:133),(R:219;G:112;B:147),
(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),
(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),
(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),
(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),
(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),
(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),
(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),
(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),
(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),
(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),
(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0),(R:  0;G:  0;B:  0));

