//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Шахматы.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Шахматы.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap achievement10 {
            get {
                object obj = ResourceManager.GetObject("achievement10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap achievement10_rollover {
            get {
                object obj = ResourceManager.GetObject("achievement10_rollover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alert {
            get {
                object obj = ResourceManager.GetObject("alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alien1dn_bmp_0 {
            get {
                object obj = ResourceManager.GetObject("alien1dn_bmp_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bishop48 {
            get {
                object obj = ResourceManager.GetObject("bishop48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap board {
            get {
                object obj = ResourceManager.GetObject("board", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap board_deff {
            get {
                object obj = ResourceManager.GetObject("board_deff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap board_deff_mini {
            get {
                object obj = ResourceManager.GetObject("board_deff_mini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap board_mini {
            get {
                object obj = ResourceManager.GetObject("board_mini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap board1 {
            get {
                object obj = ResourceManager.GetObject("board1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap board1_mini {
            get {
                object obj = ResourceManager.GetObject("board1_mini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap board2 {
            get {
                object obj = ResourceManager.GetObject("board2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap board2_mini {
            get {
                object obj = ResourceManager.GetObject("board2_mini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bpc {
            get {
                object obj = ResourceManager.GetObject("bpc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnFig_autor {
            get {
                object obj = ResourceManager.GetObject("btnFig_autor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnFig_classic {
            get {
                object obj = ResourceManager.GetObject("btnFig_classic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnFig_stok {
            get {
                object obj = ResourceManager.GetObject("btnFig_stok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fig_deff_mini {
            get {
                object obj = ResourceManager.GetObject("fig_deff_mini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fig_mini {
            get {
                object obj = ResourceManager.GetObject("fig_mini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fig1 {
            get {
                object obj = ResourceManager.GetObject("fig1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ход черных, щелкните черную фигуру, чтобы сделать ход..
        /// </summary>
        internal static string fMain_showBall_BlackGo {
            get {
                return ResourceManager.GetString("fMain_showBall_BlackGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь перекрыт другой фигурой..
        /// </summary>
        internal static string fMain_showBall_Ne {
            get {
                return ResourceManager.GetString("fMain_showBall_Ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ващему королю объявлен шах. Допустимые ходы: 1. Взять атакующую фигуру; 2. Поместить свою фигуру между атакующей фигурой и королем (если атакующая фигура не является конем); 3. Переместить короля на безопасное поле..
        /// </summary>
        internal static string fMain_showBall_SHAX {
            get {
                return ResourceManager.GetString("fMain_showBall_SHAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ход белых, щелкните белую фигуру, чтобы сделать ход..
        /// </summary>
        internal static string fMain_showBall_WhiteGo {
            get {
                return ResourceManager.GetString("fMain_showBall_WhiteGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кароль ходит на одно поле в любом направлении..
        /// </summary>
        internal static string fMain_showBall_Кароль {
            get {
                return ResourceManager.GetString("fMain_showBall_Кароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конь ходит на одно поле вверх или вниз и на два поля в сторону, либо наоборот. Конь - это единственная фигура, которая может перескакивать через другие фигуры..
        /// </summary>
        internal static string fMain_showBall_Конь {
            get {
                return ResourceManager.GetString("fMain_showBall_Конь", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ладья ходит вверх, вниз, влево или вправо на любое число полей по прямой линии..
        /// </summary>
        internal static string fMain_showBall_Ладья {
            get {
                return ResourceManager.GetString("fMain_showBall_Ладья", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пешка ходит только вперед на одно поле либо, если она стоит на начальной позиции, на два поля. Пешка может брать другие фигуры, перемещаясь на одно поле по диагонали..
        /// </summary>
        internal static string fMain_showBall_Пешка {
            get {
                return ResourceManager.GetString("fMain_showBall_Пешка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слон ходит по диагонали на любое число полей по прямой линии..
        /// </summary>
        internal static string fMain_showBall_Слон {
            get {
                return ResourceManager.GetString("fMain_showBall_Слон", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ферзь ходит в любом из восьми направлений по прямой линии..
        /// </summary>
        internal static string fMain_showBall_Ферзь {
            get {
                return ResourceManager.GetString("fMain_showBall_Ферзь", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korolev Style Pak.
        /// </summary>
        internal static string fMenu_SelectedTypeFigures_Click_Korolev_Style_Pak {
            get {
                return ResourceManager.GetString("fMenu_SelectedTypeFigures_Click_Korolev_Style_Pak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QwinCor Style Pak.
        /// </summary>
        internal static string fMenu_SelectedTypeFigures_Click_QwinCor_Style_Pak {
            get {
                return ResourceManager.GetString("fMenu_SelectedTypeFigures_Click_QwinCor_Style_Pak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--Этот файл - собственность QwinCor--&gt;
        ///&lt;!--qwinmen@yandex.ru--&gt;
        ///&lt;black Version=&quot;23.11.2014&quot;&gt;
        ///  &lt;Rose Name=&quot;up&quot; Index=&quot;0&quot; Value=&quot;38&quot; /&gt;
        ///  &lt;Rose Name=&quot;down&quot; Index=&quot;1&quot; Value=&quot;40&quot; /&gt;
        ///  &lt;Rose Name=&quot;left&quot; Index=&quot;2&quot; Value=&quot;37&quot; /&gt;
        ///  &lt;Rose Name=&quot;right&quot; Index=&quot;3&quot; Value=&quot;39&quot; /&gt;
        ///  &lt;White Name=&quot;up&quot; Index=&quot;0&quot; Value=&quot;87&quot; /&gt;
        ///  &lt;White Name=&quot;down&quot; Index=&quot;11&quot; Value=&quot;83&quot; /&gt;
        ///  &lt;White Name=&quot;left&quot; Index=&quot;22&quot; Value=&quot;65&quot; /&gt;
        ///  &lt;White Name=&quot;right&quot; Index=&quot;33&quot; Value=&quot;68&quot; /&gt;
        ///&lt;/black&gt;.
        /// </summary>
        internal static string keyControl {
            get {
                return ResourceManager.GetString("keyControl", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap king26 {
            get {
                object obj = ResourceManager.GetObject("king26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knight48 {
            get {
                object obj = ResourceManager.GetObject("knight48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Left {
            get {
                object obj = ResourceManager.GetObject("Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pawn128 {
            get {
                object obj = ResourceManager.GetObject("pawn128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap queen48 {
            get {
                object obj = ResourceManager.GetObject("queen48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Right {
            get {
                object obj = ResourceManager.GetObject("Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rook26 {
            get {
                object obj = ResourceManager.GetObject("rook26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 293
        ///149
        ///.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_конь {
            get {
                object obj = ResourceManager.GetObject("белый_конь", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_конь1 {
            get {
                object obj = ResourceManager.GetObject("белый_конь1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_конь2 {
            get {
                object obj = ResourceManager.GetObject("белый_конь2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_король {
            get {
                object obj = ResourceManager.GetObject("белый_король", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_король1 {
            get {
                object obj = ResourceManager.GetObject("белый_король1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_король2 {
            get {
                object obj = ResourceManager.GetObject("белый_король2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_ладья {
            get {
                object obj = ResourceManager.GetObject("белый_ладья", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_ладья1 {
            get {
                object obj = ResourceManager.GetObject("белый_ладья1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_ладья2 {
            get {
                object obj = ResourceManager.GetObject("белый_ладья2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_пешка {
            get {
                object obj = ResourceManager.GetObject("белый_пешка", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_пешка1 {
            get {
                object obj = ResourceManager.GetObject("белый_пешка1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_пешка2 {
            get {
                object obj = ResourceManager.GetObject("белый_пешка2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_слон {
            get {
                object obj = ResourceManager.GetObject("белый_слон", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_слон1 {
            get {
                object obj = ResourceManager.GetObject("белый_слон1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_слон2 {
            get {
                object obj = ResourceManager.GetObject("белый_слон2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_ферзь {
            get {
                object obj = ResourceManager.GetObject("белый_ферзь", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_ферзь1 {
            get {
                object obj = ResourceManager.GetObject("белый_ферзь1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap белый_ферзь2 {
            get {
                object obj = ResourceManager.GetObject("белый_ферзь2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_конь {
            get {
                object obj = ResourceManager.GetObject("черный_конь", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_конь1 {
            get {
                object obj = ResourceManager.GetObject("черный_конь1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_конь2 {
            get {
                object obj = ResourceManager.GetObject("черный_конь2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_король {
            get {
                object obj = ResourceManager.GetObject("черный_король", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_король1 {
            get {
                object obj = ResourceManager.GetObject("черный_король1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_король2 {
            get {
                object obj = ResourceManager.GetObject("черный_король2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_ладья {
            get {
                object obj = ResourceManager.GetObject("черный_ладья", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_ладья1 {
            get {
                object obj = ResourceManager.GetObject("черный_ладья1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_ладья2 {
            get {
                object obj = ResourceManager.GetObject("черный_ладья2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_пешка {
            get {
                object obj = ResourceManager.GetObject("черный_пешка", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_пешка1 {
            get {
                object obj = ResourceManager.GetObject("черный_пешка1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_пешка2 {
            get {
                object obj = ResourceManager.GetObject("черный_пешка2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_слон {
            get {
                object obj = ResourceManager.GetObject("черный_слон", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_слон1 {
            get {
                object obj = ResourceManager.GetObject("черный_слон1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_слон2 {
            get {
                object obj = ResourceManager.GetObject("черный_слон2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_ферзь {
            get {
                object obj = ResourceManager.GetObject("черный_ферзь", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_ферзь1 {
            get {
                object obj = ResourceManager.GetObject("черный_ферзь1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap черный_ферзь2 {
            get {
                object obj = ResourceManager.GetObject("черный_ферзь2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
