//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDR_MENU1                       102
#define IDD_DIALOG1                     103
#define SAMPLEDIALOG                    104
#define IDD_DialogChangeGrad            104
#define IDD_HELPDIALOG                  1000
#define ChangeOnEdit                    1002
#define IDC_EDIT_GRAD                   1002
#define IDD_ChangeOK                    1003
#define IDC_EDIT_NUMOF                  1003
#define IDC_EDIT_GRAD3                  1004
#define IDC_EDIT_SPACE                  1004
#define ID_TIMER_1                      40033
#define ID_EXIT                         40044
#define ID_40045                        40045
#define IDD_ChangeGrad                  40046
#define ID_40047                        40047
#define IDD_ChangeNumof                 40048

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40049
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
